### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by danielrussellLA** [merencia/tz-offset#4]
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

This error above ^ occurs in `tz-offset.js` when running `node-cron` on Linux machines with node `v8.11+`.
@merencia please merge this pull request https://github.com/node-cron/tz-offset/pull/3 to fix the issue.

**Comment by merencia** [comment]
Hey @danielrussellLA, thanks for your contribution. It was released on version 0.0.2.

I'll this version will be used on node-cron next release.
